[project]
name = "library1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.13.5"
dependencies = [
    "requests>=2.31.0",
    "python-json-logger>=3.3.0"
]
